### ISSUE TITLE
Module undetectable as BT device with builds between 332c30d and 625440c

### ISSUE THREAD

**Issue by mamert** [asterics/esp32_mouse_keyboard#14]
Built with 09509cd , FABI device is visible by default.
With any of the commits from the 625440c merge, no BT device is found (on Ubuntu or Windows).

Does something else need to be done first?

Monitor, boot log:
```
HEAD detached at 232ce4f

[redacted]/esp32_mouse_keyboard$ make monitor
MONITOR
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun 8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5552
ho 0 tail 12 room 4
load:0x40078000,len:0
load:0x40078000,len:12632
entry 0x40078fe4
I (30) boot: ESP-IDF v3.1-dev-661-gf586f5e 2nd stage bootloader
I (30) boot: compile time 20:32:05
I (30) boot: Enabling RNG early entropy source...
I (36) boot: SPI Speed : 40MHz
I (40) boot: SPI Mode : DIO
I (44) boot: SPI Flash Size : 4MB
I (48) boot: Partition Table:
I (52) boot: ## Label Usage Type ST Offset Length
I (59) boot: 0 nvs WiFi data 01 02 00009000 00004000
I (66) boot: 1 otadata OTA data 01 00 0000d000 00002000
I (74) boot: 2 phy_init RF data 01 01 0000f000 00001000
I (81) boot: 3 factory factory app 00 00 00010000 00200000
I (89) boot: End of partition table
```
Same from a working build:
```
HEAD detached at 09509cd

[redacted]/esp32_mouse_keyboard$ make monitor
MONITOR
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
etsRչ ��16����2��j
!��:0� �]ER�}IESQU�I��t:��3 �*��F�*�e1�Hߨ��Uj
c�K�gsZ� 0,�A�W�'��e��,k�E�v���0,\E�v:��0,�E��:��0,c.��r�'�A0�
}�r�'��0��}dr�����C!�
�iDɊ����k�V��2�!�+�i0x&֙0�Lbb��i4�!�+��0x&��00L,�+�i5�j
I (30) boot: ESP-IDF v3.1-dev-661-gf586f5e 2nd stage bootloader���002�8
I (30) boot: compile time 19:35:44
I (30) boot: Enabling RNG early entropy source...
I (36) boot: SPI Speed : 40MHz
I (40) boot: SPI Mode : DIO
I (44) boot: SPI Flash Size : 4MB
I (48) boot: Partition Table:
I (51) boot: ## Label Usage Type ST Offset Length
I (59) boot: 0 nvs WiFi data 01 02 00009000 00006000
I (66) boot: 1 phy_init RF data 01 01 0000f000 00001000
I (74) boot: 2 factory factory app 00 00 00010000 00100000
I (81) boot: End of partition table
I (85) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x378c4 (227524) map
I (174) esp_image: segment 1: paddr=0x000478ec vaddr=0x3ffc0000 size=0x03384 ( 13188) load
I (179) esp_image: segment 2: paddr=0x0004ac78 vaddr=0x40080000 size=0x00400 ( 1024) load
0x40080000: _iram_start at /home/mamert/esp/esp-idf/components/freertos/./xtensa_vectors.S:1685

I (181) esp_image: segment 3: paddr=0x0004b080 vaddr=0x40080400 size=0x04f90 ( 20368) load
I (198) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0x81d0c (531724) map
0x400d0018: _stext at ??:?

I (385) esp_image: segment 5: paddr=0x000d1d2c vaddr=0x40085390 size=0x0ab34 ( 43828) load
0x40085390: r_ld_fm_frame_isr at ??:?

I (403) esp_image: segment 6: paddr=0x000dc868 vaddr=0x400c0000 size=0x00000 ( 0) load
I (413) boot: Loaded app from partition at offset 0x10000
I (413) boot: Disabling RNG early entropy source...
I (415) cpu_start: Pro cpu up.
I (418) cpu_start: Starting app cpu, entry point is 0x40080fb8
0x40080fb8: call_start_cpu1 at /home/mamert/esp/esp-idf/components/esp32/./cpu_start.c:225

I (0) cpu_start: App cpu up.
I (429) heap_init: Initializing. RAM available for dynamic allocation:
I (436) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (442) heap_init: At 3FFCDCB8 len 00012348 (72 KiB): DRAM
I (448) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (454) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (461) heap_init: At 4008FEC4 len 0001013C (64 KiB): IRAM
I (467) cpu_start: Pro cpu start user code
I (149) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
E (238) MAIN: error reading NVS - bt name, setting to FABI
E (238) MAIN: error reading NVS - locale, setting to US_INTERNATIONAL
I (248) BTDM_INIT: BT controller compile version [ae44fa3]

I (248) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (598) phy: phy_version: 383.0, 79a622c, Jan 30 2018, 15:38:06, 0, 0
I (638) HID_DEVICE: esp_hidd_prf_cb_hdl(), start added the hid service to the stack database. incl_handle = 40
I (648) HID_DEVICE: hid svc handle = 2d```

**Comment by benjaminaigner** [comment]
But with the current master's head it is visible?

We tried many different things on the newBLE branch, but it seems like the merge was not done in one commit, but instead in single different commits on master -> not working in some stages.

Commit 09509cd used Espressif's example HID code, working with some devices.
Commit 625440c was the merge of the working BLE stack from nkolban / chegewara.

So please use either master's head (currently the 625440c merge) or 09509cd for a different approach.

Sorry for this confusion, next time I will do it manually on my PC to squash all commits from another branch...

**Comment by mamert** [comment]
Sadly, 625440c (HEAD of master) also does not work. Just checked on fresh checkout. Only non-default option is baud rate (115200). make flash, make monitor... nope, same boot log, not visible anywhere.
Tried another board, too, same result.

I tried to update because of problems with 09509cd (pe-newBLE), which I it would have been silly to ask about, with an overhaul recently done in the repo.
Shall I report anyway?
Or maybe I could help debug the current master? Which kinds of logs could be of use here?

**Comment by benjaminaigner** [comment]
@mamert 

OK, that's a problem... I will have a look and report back to you.

**Comment by benjaminaigner** [comment]
@mamert I just did a quick test, HEAD is visible on my Android 7, visible & pairable. Mouse works as well.

Which esp-idf branch/commit do you use?

I tested it with release/v3.1 and origin/master.

According to your logfile, the second boot @09509cd works as expected (as long as I remember, worked mostly on NeilKolbans CPP code for a long time).
And the first logfile is not HEAD, this is one revision before merge -> as I described before, it does not work.

Could you please provide a logfile for the current master?

Just to be sure:
* make clean (in this' repo directory)
* git checkout release/v3.1 (in esp-idf directory)
* git pull (in esp-idf directory)
* make flash monitor (in this' repo directory)

**Comment by mamert** [comment]
I've tried 9 different versions, yes, the first log is not from HEAD, but looks the same.

The sequence I was doing was: delete all files 'cept for .git, git reset --HARD, git checkout [commit#], make menuconfig, make flash, make monitor.

**Anyway, update**: Turns out my X230 w/Ubuntu, used to flash and power the modules, might not be giving enough current. When connected to a **POWERED USB HUB, 625440c also works!** Wohoo! :)
Seems that newBLE is more demanding, power-wise. I've checked again on 2 other modules: 09509cd works on unpowered hub, 625440c doesn't. Not even with an additional 10uF ceramic on the 3.3V line. No problems flashing, though, jut running the latest code.

I am very sorry for what has turned out to be a false alarm.

The reconnection problem I've had with the older version has also been solved in the latest one :)

**Comment by benjaminaigner** [comment]
@mamert 

Ok, that's good to know :-).
I was of course curious, so no worry.

One question:

* Which board do you use? It might be a USB port which handles power consumption according to the standard: 500mA only if the device enumerates correctly

Anyway, I'm happy it works for you.

**Comment by mamert** [comment]
1 "ESP32 DEVKIT V1, www.doit.am" (standard old rectangular, w/CP2102),  and 2 TTGO boards with CH340G, like this one: https://www.aliexpress.com/item/-/32846710180.html

All 3 behave exactly the same.
