### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by sandric** [asterics/esp32_mouse_keyboard#18]
Hi, sorry, I know its not very polite, and just suggestion, but is there any chance to get super basic up and running demo for library? Like after flashing you get infinite "quick brown fox" output keypress loop, that you can instantly pair with phone, see output and start playing with? I'm very new to esp32 world, looking into demo c file, it leaves in me quite a bit of frustration, I guess those `processCommand` commands are some kind of input you make to trigger keypress sending, but I'm not sure how you input those..

**Comment by benjaminaigner** [comment]
Dear Sandric,

asking is never a crime :-).
A small clarification:

This project is used to trigger mouse and keyboard actions on a paired device. These mouse/keyboard actions are input to the ESP32 via the **second** serial interface (not the programming/debugging interface, which you used via 'make flash' or 'make monitor').

Just for basic testing, we also implemented following characters, which can be typed in via the 'make monitor' console (which is UART0 of the ESP32):

* 'w'/'a'/'s'/'d': move the mouse cursor
* 'l' click left
* 'r' click right
* 'q' type in keycode for "Y"

Note: these are just for testing, if you want to try full functionality, you have to attach something to UART1, using pins 16/17 (see config.h line 14/15). UART config is done in https://github.com/asterics/esp32_mouse_keyboard/blob/master/main/ble_hidd_demo_main.cpp#L599
and set to: **8N1 @ 9600baud**

**Comment by benjaminaigner** [comment]
Regarding an example:

This project sends mouse/keyboard action immediately after you put a struct into following queues (FreeRTOS related stuff, if this is new, please read their docs before proceeding):

* **mouse_q** for mouse actions
* **keyboard_q** for mouse actions

**Comment by benjaminaigner** [comment]
For your example use case:

```
uint8_t output[] = "quick brown fox";
uint8_t i = 0;
while(output[i])
{
    sendKey(output[i], PRESS_RELEASE);
    //second option:
    //sendKey(output[i], PRESS); //send a key press event (hold it until release is sent)
    //sendKey(output[i], RELEASE); //release the key
    i++;
}
```

**Comment by sandric** [comment]
wow, thanks a lot, I reread main readme and realized second UART example, thanks a lot for your last example also, trying new things can be challenging at times but interesting.

**Comment by benjaminaigner** [comment]
Don't worry, glad to help ;-)
I had my troubles too getting started with BLE/HOG/GAP/GATT/.......
