### ISSUE TITLE
Get error message when compile:  not handled in switch [-Werror=switch]

### ISSUE THREAD

**Issue by lawleo** [asterics/esp32_mouse_keyboard#25]
components/nkolban_BLE/GeneralUtils.cpp line 450
... not handled in switch [-Werror=switch]

I simply add the following on line 508 to resolve this issue but I'm not sure if it is the correct way to do that.

    default:
        return "Unknown ESP_ERR error";

**Comment by benjaminaigner** [comment]
Dear @lawleo ,
we had the problem a few times with different versions of the esp-idf.
THX for suggesting this fix.
We switched to a different stack, should not happen there.
(merged with #27 )
