### ISSUE TITLE
esp-idf version

### ISSUE THREAD

**Issue by vignesh-mpc** [asterics/esp32_mouse_keyboard#28]
Hey, thanks for sharing this. Just wondering which version of esp-idf this should be compiled against. Would prefer to go with the esp-idf version that is known to not have any issues with this. Latest stable?

Thank you!

**Comment by benjaminaigner** [comment]
I've just compiled it with release v4.1.
I used release v3 as well.

**Comment by vignesh-mpc** [comment]
Thanks!
