### ISSUE TITLE
iOS: Assistive Touch & Switch interface

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/esp32_mouse_keyboard#34]
After a very long try&error phase with this undocumented stuff from iOS,
I can finally announce that this repository works with iOS in assistive touch mode (mouse cursor) AND switch interface (button controlled scanning).

For future references (or maybe the esp32_snippets repository), following issues were resolved:

* If the HID report map (and the corresponding attribute table) lists the mouse first, everything works fine. But iOS does NOT recognize any keyboard input as assistive switch input.
* If the report map is built up: keyboard - keyboard LEDs - consumer control - mouse; everything works exactly the same, but iOS recognizes key presses as assistive switch.
* The slave connection interval must have a value higher than 11.25ms (documented), we changed it to 12.5ms. This was no issue for normal keyboard operation & assistive touch mouse control.
* The MTU does not have any effect on the connection.

I did not find any of this behaviour documented, if somebody can show me an official guideline for this, I'm fine. Otherwise, this is another example of undocumented and senseless behaviour of Apple devices :-1: 

EDIT: I used this branch:
https://github.com/asterics/esp32_mouse_keyboard/tree/bumpEspressifExample
with this commit 74a9328

**Comment by benjaminaigner** [comment]
Closed with #35

**Comment by curiousmuch** [comment]
Can I buy you a beer for this?

**Comment by benjaminaigner** [comment]
Dear @curiousmuch 
THX, but no worries: there is enough beer in Austria :+1:
