### ISSUE TITLE
Deinit missing hidd_le_env.enabled = false;

### ISSUE THREAD

**Issue by Lars-Thestorf** [asterics/esp32_mouse_keyboard#44]
Hello,

thanks for this cool esp32 bluetooth hid example!
However I stumbled upon that
hidd_le_env.enabled = false;
seems to be missing in deinit function.

otherwise a reinit would not work.

https://github.com/asterics/esp32_mouse_keyboard/blob/d49210e2fdac4a217c0e56411834ea8c1add69d4/main/esp_hidd_prf_api.c#L92

**Comment by benjaminaigner** [comment]
Thank you very much for the hint, although we never got this issue (we simply don't deinit the HID :-)).

Greetings,
Benjamin
