### ISSUE TITLE
Demo Connects but then Disconnects / can't pass keys

### ISSUE THREAD

**Issue by schuranator** [asterics/esp32_mouse_keyboard#5]
I'm able to connect ESP32 to Windows as HID BT Keyboard / but then it disconnects.  

I added some basic debug to the GAP callback / HIDD Callback.  I'm getting a ESP_GAP_BLE_AUTH_CMPL_EVT then a few seconds later ESP_HIDD_EVENT_BLE_DISCONNECT.

Log (added basic logs to callback):
..
HIDD Callback Event:'0'
E (335) BT: esp_hidd_prf_cb_hdl(), start added the hid service to the stack database. incl_handle = 40
GAP Callback Event:'0' (ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT)
E (340) BT: hid svc handle = 2d
GAP Callback Event:'6' (When start advertising complete, the event comes)
GAP Callback Event:'10' (BLE  security request)
GAP Callback Event:'20' (When update connection parameters complete, the event comes)
GAP Callback Event:'9' (BLE  key event for peer device keys)
GAP Callback Event:'9' (BLE  key event for peer device keys)
GAP Callback Event:'8' (Authentication complete indication.)
:) E (22567) BT: status = success, ESP_GAP_BLE_AUTH_CMPL_EVT 
GAP Callback Event:'20' (When update connection parameters complete, the event comes)
GAP Callback Event:'20' (When update connection parameters complete, the event comes)
GAP Callback Event:'20' (When update connection parameters complete, the event comes)
:( HIDD Callback Event:'4' (ESP_HIDD_EVENT_BLE_DISCONNECT) ***
E (29028) BT: hidd_event_callback(), ESP_HIDD_EVENT_BLE_DISCONNECT

**Comment by benjaminaigner** [comment]
The error was related to the problem, that Windows (maybe this is related to #4 as well) requires some input for bonding (which is required for HID over GATT).

Now you need to type in a pin, which is shown on the make monitor console.
