### ISSUE TITLE
Automatic Firmware update not working

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/esp32_mouse_keyboard#56]
the automatic firmware update did not work in my recent tests,
the update process is stuck at 1% and then fails.
(tested with firmware version 0.3.0 and Win10/Win8.1/Linux PCs running the current WebGUI https://flipmouse.asterics.eu/index_fm.htm#tabGeneral)

**Comment by benjaminaigner** [comment]
If the GUI stucks at 1%, it is waiting for the
`OTA:ready` message from the ESP32.

This message is sent, when:
* There is no esp32_mouse_keyboard firmware, but the bootloader ([esp32_addon_bootloader](https://github.com/asterics/esp32_addon_bootloader))
* There is a esp32_mouse_keyboard firmware, which triggers the bootloader by the `$UG` command.

If there is no bootloader flashed on the ESP32, the updating process is not working at all,
what was your problem in this case.

**A short note:** If the `$UG` command is sent, the current firmware (esp32_mouse_keyboard) will be marked invalid, therefor the updating process is necessary!
