### ISSUE TITLE
How to swipe 

### ISSUE THREAD

**Issue by m986883511** [asterics/esp32_mouse_keyboard#60]
I test two kinds, don't work.
I think should have mouse down and mouse up.

kind 1:
```
esp_hidd_send_mouse_value(active_hid_conn_ids[i],(1<<0),0,0,0);
esp_hidd_send_mouse_value(active_hid_conn_ids[i],0,-MOUSE_SPEED,0,0);
```
kind 2:
```
esp_hidd_send_mouse_value(active_hid_conn_ids[i],(1<<0),0,MOUSE_SPEED,0);
```

**Comment by benjaminaigner** [comment]
Dear @m986883511 

please read the USB-HID specification.
Mouse buttons are absolut, so it is not possible to have "mouse button up"/"mouse button down" when directly sending the HID report (your example).

This should work;
```
//press mouse button
esp_hidd_send_mouse_value(active_hid_conn_ids[i],(1<<0),0,0,0);
//move
esp_hidd_send_mouse_value(active_hid_conn_ids[i],(1<<0),-MOUSE_SPEED,0,0);
//release mouse button
esp_hidd_send_mouse_value(active_hid_conn_ids[i],0,0,0,0);
```

I will close this issue for now, if the problem persists you can reopen it with a more detailed report.

Greetings
