### ISSUE TITLE
iOS 17 compatibility

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/esp32_mouse_keyboard#64]
Dear @tiny1990 ,

if you have a problem, please open a new issue.
It was hard to find your comment in a 2 year old closed issue.

Please describe the problem a little bit more in detail, "not working" is neither helping me nor helping you.

So, please check following or give us feedback on following aspects:
* Hardware platform, are you using our devices or a different ESP32 board?
* Please post as attachment your `sdkconfig` file
* Do you applied any changes on the sourcecode?
* Is the device visible in iOS pairing menu?
* Is the device pairing properly and shows "connected"?

Thank you, I'll try to get an iOS device for testing.

Greetings

**Comment by benjaminaigner** [comment]
@tiny1990 Any updates?

**Comment by tiny1990** [comment]
> @tiny1990 Any updates?

sorry too late, it's my fault, that's work for me

**Comment by benjaminaigner** [comment]
Dear @tiny1990 ,
thank you very much for reporting back.
So I consider iOS 17 to work with our project and I'm closing this issue now.

If anybody experiences compatibility issues with iOS 17, feel free to post here (I'd be very happy if it includes a detailed description and logfiles) and we will investigate.

Greetings
